build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

    tests-and-coverage:
      environment:
        php: 7.4

imports:
  - php

tools:
  external_code_coverage: true
